a=input("Enter your name: ")
print(a)
print(type(a))
b=input("Enter something: ")
print(b)
print(type(b))
c=input("Enter anything: ")
print(c)
c=int(c) #Typecasted string to integer(if posssible)
print(type(c))